---
title: "Benchmarking oncomix vs receptLoss"
author: "Daniel Pique"
date: "May 21, 2018"
output: html_document
---

### Step 1. Simulate gene expression data from tumor and normal tissue
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tictoc)
theme_set(theme_bw(base_size = 24, base_family = "Helvetica")) #preferred by science ##theme_hc())


numb_rows <- 1000
tum <- abs(rnorm(100000, 0, sd=1)) %>% matrix(nrow=numb_rows)
nml <- abs(rnorm(100000, 4, sd=2)) %>% matrix(nrow=numb_rows)
rownames(tum) <- paste0("gene", 1:numb_rows)
rownames(nml) <- paste0("gene", 1:numb_rows)

test_rl_res_l <- list()
test_om_res_l <- list()

for(i in 1:25){
  tic("rl")
  test_rl <- receptLoss::receptLoss(exprMatrNml = nml, exprMatrTum = tum, nSdBelow = 2, minPropPerGroup = .2)
  test_rl_res <- toc()
  test_rl_res_l[[i]] <- test_rl_res$toc - test_rl_res$tic

  tic("om")
  test_om <- oncomix::mixModelParams(exprNml = nml, exprTum = tum)
  test_om_res <- toc()
  test_om_res_l[[i]] <- test_om_res$toc - test_om_res$tic #test_om_res
}

test_rl_res_l2 <- test_rl_res_l %>% unlist
test_om_res_l2 <- test_om_res_l %>% unlist
tbl <- tibble(receptLoss=test_rl_res_l2, oncomix=test_om_res_l2) %>% gather(key = "test", value="seconds")
tbl %>% group_by(test) %>% summarise(mn = mean(seconds))
ggplot(tbl, aes(x=test, y=seconds)) + geom_boxplot() + geom_jitter(pch=21, size=2) + 
  ggtitle("Benchmarking; 2 matrices, each\nwith 100 genes x 1000 patients")

```

### Step 2. Run oncomix and receptLoss and time these.
```{r}
```


